FROM node:20-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN corepack enable && corepack prepare yarn@3.6.4 --activate
RUN yarn install
COPY . .
EXPOSE 3000
CMD ["yarn","dev","--","--host","0.0.0.0","--port","3000"]

